package com.inventorymanagementsystem.inventory.management.system.integration.data.customer;

import com.inventorymanagementsystem.inventory.management.system.data.CustomerDAO;
import com.inventorymanagementsystem.inventory.management.system.domain.Customer;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Optional;

/**
 * Author: Brian Smithers<br>
 * Date: 3/15/23<br>
 * Class: CustomerDAODeleteIT<br>
 * Description:
 */
public class DeleteIT {

    private CustomerDAO customerDAO;

    @BeforeEach
    public void setUp() {
        customerDAO = new CustomerDAO();
    }

    /**
     * Author: Brian Smithers<br>
     * Date: 3/15/23<br>
     * Method: deleteAValidCustomerByCustomerId<br>
     * Description:
     */
    @Test
    public void deleteAValidCustomerByCustomerId() {
        // Arrange
        long customerId = 26L;

        Customer customer = new Customer(customerId, "Frank", "Hollow", "1237 Imaginery Lane",
                "8641246710", "fhollow@ggc.edu", null);
        Optional<Customer> optionalCustomer;

        // Act
        customerDAO.delete(customer);
        optionalCustomer = customerDAO.get(customerId); // This long value is generated by the database.

        // Assert
        Assertions.assertEquals(Optional.empty(), optionalCustomer,
                "This value should return Optional.empty if the customer was deleted.");
    }
}
